// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cpu": {
            "post": {
                "description": "Perform CPU spike injection. Provide a percentage and the cpu usage will increase based on it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Failure injections"
                ],
                "summary": "Inject CPU failures",
                "parameters": [
                    {
                        "enum": [
                            "start",
                            "recover"
                        ],
                        "type": "string",
                        "description": "Specify to perform a start or a recover for the CPU injection",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Specify the job name, percentage and target",
                        "name": "requestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cpu.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Payload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/docker": {
            "post": {
                "description": "Perform start or stop action on a container. If random is specified you do not have to provide a target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Failure injections"
                ],
                "summary": "Inject docker failures",
                "parameters": [
                    {
                        "enum": [
                            "random"
                        ],
                        "type": "string",
                        "description": "Specify to perform action for container on random target",
                        "name": "do",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "kill",
                            "recover"
                        ],
                        "type": "string",
                        "description": "Specify to perform a recover or a kill on the specified container",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Specify the job name, container name and target",
                        "name": "requestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docker.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Payload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/master/status": {
            "get": {
                "description": "Bot status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Status"
                ],
                "summary": "get master status",
                "responses": {
                    "200": {
                        "description": "Bots status",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/network": {
            "post": {
                "description": "Start and stop network failures",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Failure injections"
                ],
                "summary": "Inject network failures",
                "parameters": [
                    {
                        "enum": [
                            "start",
                            "recover"
                        ],
                        "type": "string",
                        "description": "Specify to perform a start or recover for a network failure injection",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Specify the job name, device name, target and netem injection arguments",
                        "name": "requestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/network.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Payload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/recover/alertmanager": {
            "post": {
                "description": "Alertmanager webhook to recover from failures",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recover"
                ],
                "summary": "recover from failures",
                "parameters": [
                    {
                        "description": "Create request payload that contains the recovery details",
                        "name": "RequestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recover.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RecoverResponsePayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/server": {
            "post": {
                "description": "Perform Server fault injection. Supports action to kill the server specified. A shutdown will be executed after 1 minute.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Failure injections"
                ],
                "summary": "Inject Server failures",
                "parameters": [
                    {
                        "enum": [
                            "kill"
                        ],
                        "type": "string",
                        "description": "Specify to perform a kill action on the server",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Specify the job name and target",
                        "name": "requestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Payload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/service": {
            "post": {
                "description": "Perform start or stop action on a service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Failure injections"
                ],
                "summary": "Inject service failures",
                "parameters": [
                    {
                        "enum": [
                            "kill",
                            "recover"
                        ],
                        "type": "string",
                        "description": "Specify to perform a recover or a kill on the specified service",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Specify the job name, service name and target",
                        "name": "requestPayload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Payload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cpu.RequestPayload": {
            "type": "object",
            "properties": {
                "job": {
                    "type": "string"
                },
                "percentage": {
                    "type": "integer"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "docker.RequestPayload": {
            "type": "object",
            "properties": {
                "containerName": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "network.RequestPayload": {
            "type": "object",
            "properties": {
                "corrupt correlation": {
                    "type": "number"
                },
                "corrupt probability": {
                    "type": "number"
                },
                "delay correlation": {
                    "type": "number"
                },
                "device": {
                    "type": "string"
                },
                "duplicate": {
                    "type": "number"
                },
                "duplicate correlation": {
                    "type": "number"
                },
                "gap": {
                    "type": "integer"
                },
                "jitter": {
                    "type": "integer"
                },
                "job": {
                    "type": "string"
                },
                "latency": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "loss": {
                    "type": "number"
                },
                "loss correlation": {
                    "type": "number"
                },
                "reorder correlation": {
                    "type": "number"
                },
                "reorder probability": {
                    "type": "number"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "recover.Alert": {
            "type": "object",
            "properties": {
                "labels": {
                    "$ref": "#/definitions/recover.Labels"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "recover.Labels": {
            "type": "object",
            "properties": {
                "recoverAll": {
                    "type": "boolean"
                },
                "recoverJob": {
                    "type": "string"
                },
                "recoverTarget": {
                    "type": "string"
                }
            }
        },
        "recover.RequestPayload": {
            "type": "object",
            "properties": {
                "alerts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recover.Alert"
                    }
                }
            }
        },
        "response.Payload": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.RecoverMessage": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.RecoverResponsePayload": {
            "type": "object",
            "properties": {
                "recoverMessages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RecoverMessage"
                    }
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "server.RequestPayload": {
            "type": "object",
            "properties": {
                "job": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "service.RequestPayload": {
            "type": "object",
            "properties": {
                "job": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8090",
	BasePath:    "/chaos/api/v1",
	Schemes:     []string{},
	Title:       "Chaos Master API",
	Description: "This is the chaos master API.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
