api_options:
  port: 8090
  scheme: http

jobs:
  - job_name: "zookeeper docker"
    type: "Docker"
    component_name: "zookeeper"
    targets: ['127.0.0.1:8083', '127.0.0.1:8081']
  - job_name: "zookeeper service"
    type: "Service"
    component_name: "simple"
    targets: ['127.0.0.1:8082', '127.0.0.1:8081']
  - job_name: "zookeeper_docker"
    type: "Docker"
    component_name: "test"
    targets: ['127.0.0.1:8082', '127.0.0.1:8081']
  - job_name: "zookeeper_service"
    type: "Service"
    component_name: "test"
    targets: ['127.0.0.1:8081']
  - job_name: "cpu_injection"
    type: "CPU"
    targets: ['127.0.0.1:8081']

health_check_report: true